PRACTICE EXERCISE :-


1. CREATE TABLE Countries(CountryId INT NOT NULL UNIQUE,CountryName VARCHAR(10) CHECK(CountryName IN('Italy','India','China')),RegionId INT NOT NULL);

2. CREATE TABLE JobHistory(EmployeeId INT NOT NULL PRIMARY KEY,StartDate DATE NOT NULL,EndDate DATE NOT NULL,CHECK (EndDate LIKE '--/--/----'),JobId INT NOT NULL,DepartmentId INT NOT NULL);

3. CREATE TABLE Jobs(JobId INT NOT NULL PRIMARY KEY,JobTitle VARCHAR(10),MinSalary VARCHAR(20) DEFAULT '8000',MaxSalary VARCHAR(20) DEFAULT 'NULL');

4. CREATE TABLE Employees(EmployeeId INT NOT NULL PRIMARY KEY,FirstName VARCHAR(20),LastName VARCHAR(20),Email VARCHAR(25),PhoneNumber VARCHAR(10),HireDate DATE ,JobId INT NOT NULL,Salary VARCHAR(20),Commission VARCHAR(10),ManagerID INT NOT NULL,DepartmentId INT NOT NULL,FOREIGN KEY (DepartmentId) REFERENCES Departments(DepartmentId),FOREIGN KEY (JobId) REFERENCES Jobs(JobId));

ALTER :-

1. ALTER TABLE JobHistory ADD CONSTRAINT fk_JobId FOREIGN KEY (JobId) REFERENCES JobHistory(EmployeeId);

2. ALTER TABLE JobHistory DROP fk_JobId ;

3. ALTER TABLE JobHistory ADD Location varchar(50);

ASSIGNMENT :-

CREATE TABLE SalesPerson(EmployeeId INT NOT NULL PRIMARY KEY,EmployeeName VARCHAR(20),Commission VARCHAR(10));

CREATE TABLE Cars(CarId INT NOT NULL PRIMARY KEY,CarName VARCHAR(20),ModelId INT NOT NULL);

CREATE TABLE Model(ModelId INT FOREIGN KEY REFERENCES Cars(CarId) ,ModelName VARCHAR(20),Price VARCHAR(20));

CREATE TABLE Sales(BillNo INT NOT NULL PRIMARY KEY,ModelId INT FOREIGN KEY REFERENCES Cars(CarId),EmployeeId INT REFERENCES SalesPerson(EmployeeId));  



